# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_USER
# DOCKER_PASS
#

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Build
          command: |
            docker build -t mozilla/remote-settings-uptake-health:$CIRCLE_SHA1 .

      - run:
          name: Test
          command: |
            docker run -t mozilla/remote-settings-uptake-health:$CIRCLE_SHA1 test

      - run:
          name: Lint check
          command: |
            docker run -t mozilla/remote-settings-uptake-health:$CIRCLE_SHA1 lintcheck

      - run:
          name: Push to Dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh latest
            fi
            if [ -n "${CIRCLE_TAG}" ]; then
              ./deploy.sh "$CIRCLE_TAG"
            fi
